"""init schema

Revision ID: 1bb5d0025eaf
Revises: 
Create Date: 2026-07-23 23:25:03.382668
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1bb5d0025eaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishconcept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('search_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuisine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('cooking_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_veg', sa.Boolean(), nullable=False),
    sa.Column('allergens', sa.JSON(), nullable=False),
    sa.Column('heaviness', sa.Integer(), nullable=False),
    sa.Column('spice_level', sa.Integer(), nullable=False),
    sa.Column('typical_calories', sa.Integer(), nullable=False),
    sa.Column('typical_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('swiggy_address_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_concept_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('menu_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('restaurant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('restaurant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('is_ad', sa.Boolean(), nullable=False),
    sa.Column('offer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dish_concept_id'], ['dishconcept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_address_id'), 'offer', ['address_id'], unique=False)
    op.create_index(op.f('ix_offer_dish_concept_id'), 'offer', ['dish_concept_id'], unique=False)
    op.create_table('profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('avoided_ingredients', sa.JSON(), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_band', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuisines', sa.JSON(), nullable=False),
    sa.Column('adventure_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('routine',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profession', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_days', sa.JSON(), nullable=False),
    sa.Column('work_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lifestyle_habits', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hunger', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget_override', sa.Integer(), nullable=True),
    sa.Column('companions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_available_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_session_id'), 'deck', ['session_id'], unique=False)
    op.create_table('deckcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('dish_concept_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['dish_concept_id'], ['dishconcept.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deckcard_deck_id'), 'deckcard', ['deck_id'], unique=False)
    op.create_table('mealfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_card_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_card_id'], ['deckcard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealfeedback_deck_card_id'), 'mealfeedback', ['deck_card_id'], unique=False)
    op.create_table('swipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_card_id', sa.Integer(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_card_id'], ['deckcard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipe_deck_card_id'), 'swipe', ['deck_card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipe_deck_card_id'), table_name='swipe')
    op.drop_table('swipe')
    op.drop_index(op.f('ix_mealfeedback_deck_card_id'), table_name='mealfeedback')
    op.drop_table('mealfeedback')
    op.drop_index(op.f('ix_deckcard_deck_id'), table_name='deckcard')
    op.drop_table('deckcard')
    op.drop_index(op.f('ix_deck_session_id'), table_name='deck')
    op.drop_table('deck')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_table('session')
    op.drop_table('routine')
    op.drop_table('profile')
    op.drop_index(op.f('ix_offer_dish_concept_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_address_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    op.drop_table('dishconcept')
    # ### end Alembic commands ###
